[package]
name = "dnutils"
authors = ["Veirt <vveirt@gmail.com>"]
description = "A collection of Dragon Nest development utilities."
license = "GPL-3.0"
version = "0.1.4"
edition = "2021"

[dependencies]
dnpak = "2.0.0"
# dnpak = { path = "../dnpak-rs"}
